### ISSUE TITLE
Sort by table calcs

### ISSUE THREAD

**Issue by LookerCD** [savagewill/chris_feature_requests#1]
I really want this.

**Comment by savagewill** [comment]
Already in /looker/analytics

**Comment by savagewill** [comment]
no dupes plz

**Comment by LookerCD** [comment]
I'm having trouble keeping a straight face with this.

On Fri, May 15, 2015 at 10:54 AM, Will Savage notifications@github.com
wrote:

> no dupes plz
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/savagewill/chris_feature_requests/issues/1#issuecomment-102471239
> .

## 

http://www.looker.com/
*Chris Daniel *| Inside Sales
http://www.linkedin.com/pub/chris-daniel/77/b30/215/
M: (916) 616-9748 | www.looker.com
O: (831) 244-0340 | Want to chat? Book some time on my calendar.
https://cdan.youcanbook.me/

**Comment by savagewill** [comment]
:+1:

**Comment by savagewill** [comment]
@LookerCD hey we can do this now!
